import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {runNamedDeclarations,extractNamedDeclaration,evaluateExpression} from './runtime-vm-fixture.mjs';
import {assertCurrentReleaseIdentity,RELEASE_METADATA} from './release-metadata-test-helper.mjs';
const read=file=>fs.readFileSync(new URL('../'+file,import.meta.url),'utf8');
const {buildId:BUILD,displayVersion:VERSION}=RELEASE_METADATA;
function quotaStorage(initial,limit){const map=new Map(Object.entries(initial).map(([k,v])=>[String(k),String(v)]));const size=()=>Array.from(map,([k,v])=>k.length+v.length).reduce((a,b)=>a+b,0);return {getItem:k=>map.has(String(k))?map.get(String(k)):null,setItem(k,v){k=String(k);v=String(v);const old=map.get(k)||'';if(size()-k.length-old.length+k.length+v.length>limit){const e=Error('quota');e.name='QuotaExceededError';throw e;}map.set(k,v);},removeItem:k=>map.delete(String(k)),snapshot:()=>Object.fromEntries(map)};}
test('1.7.73 persistence and verified successors use canonical release metadata and TEST Supabase',()=>{assertCurrentReleaseIdentity(read,'1.7.73');});
test('newer legacy snapshot migrates into one canonical cache at storage limit',()=>{const stale={months:{'5/26':{notes:[]}}},current={months:{'9/26':{notes:[{text:'current'}]},'10/26':{notes:[]}}},legacy={updatedAt:123,version:'1.7.72',rotation:current,machineSettingsRows:[],announcements:[]};const initial={rotace_kalkulacky_state_v123:JSON.stringify(stale),rotace_supabase_local_state_v1:JSON.stringify(legacy)};const limit=Object.entries(initial).reduce((n,[k,v])=>n+k.length+v.length,0),localStorage=quotaStorage(initial,limit),state={announcements:[],cacheGuard:{}};const {api}=runNamedDeclarations({modules:[{source:read('supabase-bridge.js'),names:['LOCAL_STATE_KEY','LOCAL_ROTATION_KEY','LOCAL_MACHINE_SETTINGS_KEY','safeReadJson','safeWriteJson','readCanonicalRotationState','writeCanonicalRotationState','saveLocalSnapshot','readLocalSnapshot','loadCachedRotationState']}],globals:{localStorage,state,window:{APP_VERSION:VERSION}},exports:{load:'loadCachedRotationState'}});assert.deepEqual(structuredClone(api.load().payload),current);const stored=localStorage.snapshot();assert.deepEqual(JSON.parse(stored.rotace_kalkulacky_state_v123),current);const compact=JSON.parse(stored.rotace_supabase_local_state_v1);assert.equal(compact.rotation,null);assert.equal(compact.rotationKey,'rotace_kalkulacky_state_v123');assert.equal(state.cacheGuard.rotationStorageError,'');assert.equal(state.cacheGuard.rotationCacheMigrations,1);});
function flushFixture(task,remoteRow){let queue=[structuredClone(task)];const q={select(){return this;},eq(){return this;},order(){return this;},async limit(){return {data:remoteRow?[structuredClone(remoteRow)]:[],error:null};},async maybeSingle(){return {data:remoteRow?structuredClone(remoteRow):null,error:null};}};const c={flushPromise:null,navigator:{onLine:true},document:{visibilityState:'visible'},state:{queueGuard:{storageError:''},syncGuard:{queueFlushRuns:0,queueFlushErrors:0,queueFlushEmptyRuns:0,queueFlushSuccesses:0,queueConflictHolds:0}},getClient:()=>({from:()=>q}),readQueue:()=>queue.map(item=>structuredClone(item)),writeQueue:v=>{queue=v.map(item=>structuredClone(item));return true;},rememberQueueHealth:v=>({length:v.length}),shouldDeferQueueFlushForHiddenPage:()=>false,SUPABASE_QUEUE_FLUSH_BATCH_SIZE:8,SUPABASE_QUEUE_FLUSH_IDLE_DELAY_MS:1200,SUPABASE_QUEUE_HIDDEN_RETRY_DELAY_MS:1800,getNextQueueRetryAt:()=>null,shouldSkipQueuedTaskForBackoff:()=>false,markQueuedTaskAttempt:v=>({...v,lastTriedAt:Date.now()}),markQueuedTaskFailure:(v,e)=>({...v,retryCount:(v.retryCount||0)+1,lastErrorMessage:e.message}),isLikelyPermanentQueueError:()=>false,isLikelyOfflineError:()=>false,scheduleSupabaseQueueFlush:()=>true,runSupabaseOperation:async(_n,a)=>await a(),GAME_UI_SETTINGS_TYPE:'__profile_ui',window:{__rakRefreshSyncBadgeTruth:()=>{}},console:{warn:()=>{}},Date,JSON,Promise,Map,Set,structuredClone};const fn=extractNamedDeclaration(read('supabase-bridge.js'),'flushPendingWrites');return {run:evaluateExpression('('+fn+')',c),queue:()=>queue};}
test('already-conflicted automatic local seed is rechecked and removed read-only',async()=>{const f=flushFixture({id:'old',type:'rotation_state',queuedAt:'2026-09-22T08:00:00.000Z',conflict:'admin-review-required',meta:{source:'local-seed'},rotation:{months:{'5/26':{}}}},{key:'main',revision:7});const r=await f.run();assert.equal(r.ok,true);assert.equal(r.flushed,1);assert.equal(r.held,0);assert.equal(f.queue().length,0);});
test('service worker refuses incomplete offline runtime',()=>{const sw=read('sw.js');for(const m of ['const OFFLINE_REQUIRED = Object.freeze([','for (const url of OFFLINE_REQUIRED)',"'./core.js?v=1.7.0'","'./rotace.js?v=1.7.0'","'./supabase-bridge.js?v=1.7.0'","'./app-rotation-sync.js?v=1.7.0'",'incomplete offline runtime'])assert(sw.includes(m),'missing '+m);});
test('browser regression covers divergent cache migration and offline restart',()=>{const b=read('tools/browser-offline-17052.mjs');for(const m of ['RAK-CI-OFFLINE-17077','rotace_kalkulacky_state_v123','canonicalMarker:true','singleCopy:true'])assert(b.includes(m),'missing '+m);const w=read('.github/workflows/rak-development-validation.yml');assert(w.includes('node --test tools/release-gate-17073.test.mjs'));assert(w.includes('rak-170'+VERSION.split('.').at(-1)+'-isolated-build-'));});

