create table if not exists public.hradnik_sources (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  name text not null,
  base_url text not null,
  enabled boolean not null default true,
  priority integer not null default 100,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hradnik_places (
  id bigint generated by default as identity primary key,
  source_key text not null default 'seed',
  external_id text,
  slug text not null,
  name text not null,
  kind text not null check (kind in ('Hrad','Zámek','Zřícenina','Tvrz','Klášter','Opevněné místo','Jiné dochované místo')),
  character text,
  district text,
  region text,
  municipality text,
  latitude double precision,
  longitude double precision,
  description text,
  official_url text,
  ticket_url text,
  opening_hours jsonb not null default '{}'::jsonb,
  ticket_prices jsonb not null default '{}'::jsonb,
  photo_urls jsonb not null default '[]'::jsonb,
  source_url text,
  source_updated_at timestamptz,
  last_verified_at timestamptz,
  is_visible boolean not null default true,
  is_current boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_key, external_id),
  check (latitude is null or latitude between 48 and 52),
  check (longitude is null or longitude between 12 and 19)
);
create index if not exists hradnik_places_name_idx on public.hradnik_places (name);
create index if not exists hradnik_places_district_idx on public.hradnik_places (district);
create index if not exists hradnik_places_region_idx on public.hradnik_places (region);
create index if not exists hradnik_places_kind_idx on public.hradnik_places (kind);
create index if not exists hradnik_places_geo_idx on public.hradnik_places (latitude, longitude);

create table if not exists public.hradnik_place_sources (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.hradnik_places(id) on delete cascade,
  source_key text not null references public.hradnik_sources(source_key) on update cascade,
  source_url text not null,
  source_label text,
  fetched_at timestamptz not null default now(),
  confidence numeric(4,3) check (confidence between 0 and 1),
  unique(place_id, source_key)
);

create table if not exists public.hradnik_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','success','partial','failed')),
  discovered integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  hidden_count integer not null default 0,
  error_count integer not null default 0,
  sources jsonb not null default '[]'::jsonb,
  message text
);

create table if not exists public.hradnik_sync_control (
  id boolean primary key default true check (id=true),
  sync_key text not null,
  updated_at timestamptz not null default now()
);
insert into public.hradnik_sync_control(id,sync_key) values(true,'AiBj8MpPgQ5RdQbjVsHbM_zv9F2FHdK5Rkjd4fPAmFc') on conflict(id) do update set sync_key=excluded.sync_key,updated_at=now();
insert into public.hradnik_sources(source_key,name,base_url,enabled,priority) values
('hrady_zriceniny','Hrady-zříceniny.cz','https://www.hrady-zriceniny.cz/',true,10),
('npu','Národní památkový ústav','https://www.npu.cz/',true,20)
on conflict(source_key) do update set name=excluded.name,base_url=excluded.base_url,enabled=excluded.enabled,priority=excluded.priority,updated_at=now();

create or replace function public.hradnik_touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists hradnik_sources_updated_at on public.hradnik_sources;
create trigger hradnik_sources_updated_at before update on public.hradnik_sources for each row execute function public.hradnik_touch_updated_at();
drop trigger if exists hradnik_places_updated_at on public.hradnik_places;
create trigger hradnik_places_updated_at before update on public.hradnik_places for each row execute function public.hradnik_touch_updated_at();

alter table public.hradnik_sources enable row level security;
alter table public.hradnik_places enable row level security;
alter table public.hradnik_place_sources enable row level security;
alter table public.hradnik_sync_runs enable row level security;
alter table public.hradnik_sync_control enable row level security;
drop policy if exists hradnik_sources_public_read on public.hradnik_sources;
create policy hradnik_sources_public_read on public.hradnik_sources for select to anon,authenticated using(enabled=true);
drop policy if exists hradnik_places_public_read on public.hradnik_places;
create policy hradnik_places_public_read on public.hradnik_places for select to anon,authenticated using(is_visible=true and is_current=true);
drop policy if exists hradnik_place_sources_public_read on public.hradnik_place_sources;
create policy hradnik_place_sources_public_read on public.hradnik_place_sources for select to anon,authenticated using(true);
grant select on public.hradnik_sources to anon,authenticated;
grant select on public.hradnik_places to anon,authenticated;
grant select on public.hradnik_place_sources to anon,authenticated;

insert into public.hradnik_places(source_key,external_id,slug,name,kind,character,district,region,latitude,longitude,is_visible,is_current) values
('seed','b1','bitov','Bítov','Hrad','hrad','Znojmo','Jihomoravský kraj',48.9417,15.6969,true,true),
('seed','c1','cornstejn','Cornštejn','Zřícenina','zřícenina hradu','Znojmo','Jihomoravský kraj',48.9471,15.6870,true,true),
('seed','v1','vranov-nad-dyji','Vranov nad Dyjí','Zámek','hrad přestavěný na zámek','Znojmo','Jihomoravský kraj',48.8948,15.8122,true,true),
('seed','p1','pernstejn','Pernštejn','Hrad','hrad','Brno-venkov','Jihomoravský kraj',49.4545,16.3174,true,true),
('seed','be','bezdez','Bezděz','Hrad','hrad','Česká Lípa','Liberecký kraj',50.5397,14.7224,true,true),
('seed','kr','krivoklat','Křivoklát','Hrad','hrad','Rakovník','Středočeský kraj',50.0379,13.8728,true,true),
('seed','ka','karlstejn','Karlštejn','Hrad','hrad','Beroun','Středočeský kraj',49.9397,14.1870,true,true),
('seed','ko','kost','Kost','Hrad','hrad','Jičín','Královéhradecký kraj',50.4910,15.1342,true,true),
('seed','tr','trosky','Trosky','Zřícenina','zřícenina hradu','Semily','Liberecký kraj',50.5157,15.2308,true,true),
('seed','bo','bouzov','Bouzov','Hrad','hrad','Olomouc','Olomoucký kraj',49.7042,16.8923,true,true),
('seed','ra','rabi','Rabí','Zřícenina','zřícenina hradu','Klatovy','Plzeňský kraj',49.2776,13.4897,true,true),
('seed','hl','hluboka','Hluboká nad Vltavou','Zámek','zámek','České Budějovice','Jihočeský kraj',49.0519,14.4427,true,true),
('seed','ro','rozmberk','Rožmberk nad Vltavou','Hrad','hrad','Český Krumlov','Jihočeský kraj',48.8554,14.3658,true,true),
('seed','zv','zvikov','Zvíkov','Hrad','hrad','Písek','Jihočeský kraj',49.4384,14.2069,true,true),
('seed','ok','okor','Okoř','Zřícenina','zřícenina hradu','Praha-západ','Středočeský kraj',50.1618,14.2601,true,true),
('seed','ko2','kokorin','Kokořín','Hrad','hrad','Mělník','Středočeský kraj',50.4382,14.5794,true,true),
('seed','ka2','kasperk','Kašperk','Hrad','hrad','Klatovy','Plzeňský kraj',49.1694,13.5529,true,true),
('seed','ku','kuneticka-hora','Kunětická hora','Hrad','hrad','Pardubice','Pardubický kraj',50.0724,15.8085,true,true),
('seed','le','lednice','Lednice','Zámek','zámek','Břeclav','Jihomoravský kraj',48.7998,16.8035,true,true),
('seed','sy','sychrov','Sychrov','Zámek','zámek','Liberec','Liberecký kraj',50.6276,15.0902,true,true)
on conflict(source_key,external_id) do nothing;
;
